// GENERATED by scripts/sync-palettes.mjs from basecamp/omarchy@81145eb. Do not edit by hand.

export interface Palette {
	id: string;
	name: string;
	mode: "light" | "dark";
	/** [background, foreground, accent] for the picker swatch */
	swatch: [string, string, string];
}

export const palettes: Palette[] = [
	{
		"id": "catppuccin-latte",
		"name": "Catppuccin Latte",
		"mode": "light",
		"swatch": [
			"#eff1f5",
			"#4c4f69",
			"#1e66f5"
		]
	},
	{
		"id": "flexoki-light",
		"name": "Flexoki Light",
		"mode": "light",
		"swatch": [
			"#fffcf0",
			"#100f0f",
			"#205ea6"
		]
	},
	{
		"id": "lupine",
		"name": "Lupine",
		"mode": "light",
		"swatch": [
			"#fafafa",
			"#212121",
			"#3264eb"
		]
	},
	{
		"id": "rose-pine",
		"name": "Rose Pine",
		"mode": "light",
		"swatch": [
			"#faf4ed",
			"#575279",
			"#56949f"
		]
	},
	{
		"id": "white",
		"name": "White",
		"mode": "light",
		"swatch": [
			"#ffffff",
			"#000000",
			"#6e6e6e"
		]
	},
	{
		"id": "catppuccin",
		"name": "Catppuccin",
		"mode": "dark",
		"swatch": [
			"#1e1e2e",
			"#cdd6f4",
			"#89b4fa"
		]
	},
	{
		"id": "ethereal",
		"name": "Ethereal",
		"mode": "dark",
		"swatch": [
			"#060b1e",
			"#ffcead",
			"#7d82d9"
		]
	},
	{
		"id": "everforest",
		"name": "Everforest",
		"mode": "dark",
		"swatch": [
			"#2d353b",
			"#d3c6aa",
			"#7fbbb3"
		]
	},
	{
		"id": "gruvbox",
		"name": "Gruvbox",
		"mode": "dark",
		"swatch": [
			"#282828",
			"#d4be98",
			"#7daea3"
		]
	},
	{
		"id": "hackerman",
		"name": "Hackerman",
		"mode": "dark",
		"swatch": [
			"#0b0c16",
			"#ddf7ff",
			"#82fb9c"
		]
	},
	{
		"id": "kanagawa",
		"name": "Kanagawa",
		"mode": "dark",
		"swatch": [
			"#1f1f28",
			"#dcd7ba",
			"#dcd7ba"
		]
	},
	{
		"id": "last-horizon",
		"name": "Last Horizon",
		"mode": "dark",
		"swatch": [
			"#0c0b0c",
			"#fafcfb",
			"#b59790"
		]
	},
	{
		"id": "lumon",
		"name": "Lumon",
		"mode": "dark",
		"swatch": [
			"#16242d",
			"#d6e2ee",
			"#8bc9eb"
		]
	},
	{
		"id": "matte-black",
		"name": "Matte Black",
		"mode": "dark",
		"swatch": [
			"#121212",
			"#bebebe",
			"#e68e0d"
		]
	},
	{
		"id": "miasma",
		"name": "Miasma",
		"mode": "dark",
		"swatch": [
			"#222222",
			"#c2c2b0",
			"#78824b"
		]
	},
	{
		"id": "nord",
		"name": "Nord",
		"mode": "dark",
		"swatch": [
			"#2e3440",
			"#d8dee9",
			"#81a1c1"
		]
	},
	{
		"id": "osaka-jade",
		"name": "Osaka Jade",
		"mode": "dark",
		"swatch": [
			"#111c18",
			"#c1c497",
			"#509475"
		]
	},
	{
		"id": "retro-82",
		"name": "Retro 82",
		"mode": "dark",
		"swatch": [
			"#05182e",
			"#f6dcac",
			"#faa968"
		]
	},
	{
		"id": "ristretto",
		"name": "Ristretto",
		"mode": "dark",
		"swatch": [
			"#2c2525",
			"#e6d9db",
			"#f38d70"
		]
	},
	{
		"id": "solitude",
		"name": "Solitude",
		"mode": "dark",
		"swatch": [
			"#101315",
			"#cacccc",
			"#798186"
		]
	},
	{
		"id": "tokyo-night",
		"name": "Tokyo Night",
		"mode": "dark",
		"swatch": [
			"#1a1b26",
			"#a9b1d6",
			"#7aa2f7"
		]
	},
	{
		"id": "vantablack",
		"name": "Vantablack",
		"mode": "dark",
		"swatch": [
			"#000000",
			"#ffffff",
			"#8d8d8d"
		]
	}
];

export const paletteIds = new Set(palettes.map((palette) => palette.id));
